apiVersion: v1
kind: Service
metadata:
  name: service1-svc
spec:
  ports:
    - nodePort: 31917
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1-deployment
spec:
  selector:
    matchLabels:
      app: service1
  replicas: 1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: mabutkovic/service1:latest
          ports:
            - containerPort: 8080