apiVersion: v1
kind: Service
metadata:
  name: service1-svc
spec:
  ports:
    - nodePort: 31917
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service1
  type: NodePort